RESULT = custom_dx
SOURCES = \
  map_type.mli map_type.ml \
  utility.mli utility.ml \
  CertReader/certificate.mli CertReader/certificate.ml \
  compiler_meta.mli compiler_meta.ml \
  CertReader/default_methods.mli CertReader/default_methods.ml \
  CertReader/cert_reader.mli CertReader/cert_reader.ml \
  JVMReader/constant.mli JVMReader/constant.ml \
  JVMReader/handler.mli JVMReader/handler.ml \
  JVMReader/instructions.mli JVMReader/instructions.ml \
  JVMReader/parse_byte.mli JVMReader/parse_byte.ml \
  JVMReader/attributes.mli JVMReader/attributes.ml \
  JVMReader/constant_parsing.mli JVMReader/constant_parsing.ml \
  JVMReader/JVM_Method.mli JVMReader/JVM_Method.ml \
  JVMReader/JVM_Class.mli JVMReader/JVM_Class.ml \
  TypeInference/flow_tracer.mli TypeInference/flow_tracer.ml \
  TypeInference/type_assigner.mli TypeInference/type_assigner.ml \
  TypeInference/type_inference.mli TypeInference/type_inference.ml \
  Translation/pick_order.mli Translation/pick_order.ml \
  Translation/start_block.mli Translation/start_block.ml \
  Translation/stackValTypeAssigner.mli Translation/stackValTypeAssigner.ml \
  Translation/trace_parent_child.mli Translation/trace_parent_child.ml \
  Translation/translate_java_program.mli Translation/translate_java_program.ml \
  Translation/consolidate_block.mli Translation/consolidate_block.ml \
  main.ml
  
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)  
